"""
generate_epaper_cards_json.py
--------------------------------

Create a small, ESP32/e-paper-friendly JSON feed from the full Pokémon card
price CSV generated by download_pokemon_tcgcsv_json.py.

The full CSV is kept as the archival dataset. This JSON is intentionally a
screen-ready subset so an ESP32 does not need to download and parse several MB
of CSV data.

Usage:

    python generate_epaper_cards_json.py \
      --input cards/pokemon_cards.csv \
      --output cards/epaper_cards.json \
      --limit 300

Output schema:

{
  "schemaVersion": 1,
  "source": "tcgcsv",
  "sourceUpdatedAt": "2026-07-24T20:11:00+0000",
  "generatedAt": "2026-07-25T00:00:00Z",
  "totalRows": 46455,
  "cardsIncluded": 300,
  "selection": {
    "limit": 300,
    "requireMarketPrice": true,
    "order": "csv_order_newest_groups_first"
  },
  "cards": [
    {
      "id": 696613,
      "set": "ME: 30th Celebration",
      "name": "30th Celebration Pack",
      "rarity": null,
      "type": "Normal",
      "market": 34.43,
      "mid": 29.96,
      "low": 28.95,
      "high": 155.49,
      "priceStatus": "ok"
    }
  ]
}
"""

from __future__ import annotations

import argparse
import csv
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional
from urllib.request import Request, urlopen

LAST_UPDATED_URL = "https://tcgcsv.com/last-updated.txt"
USER_AGENT = "LuckyDog-ESP32-Epaper-PokemonPriceSync/1.0"


def parse_price(value: str) -> Optional[float]:
    value = (value or "").strip()
    if not value:
        return None
    try:
        return round(float(value), 2)
    except ValueError:
        return None


def clean_text(value: str) -> Optional[str]:
    value = (value or "").strip()
    return value or None


def fetch_source_updated_at(timeout: int = 20) -> Optional[str]:
    req = Request(LAST_UPDATED_URL, headers={"User-Agent": USER_AGENT})
    try:
        with urlopen(req, timeout=timeout) as resp:
            return resp.read().decode("utf-8", errors="replace").strip() or None
    except Exception:
        return None


def row_to_card(row: Dict[str, str]) -> Dict[str, Any]:
    market = parse_price(row.get("marketPrice", ""))
    card = {
        "id": int(row["productId"]) if row.get("productId", "").isdigit() else row.get("productId"),
        "set": clean_text(row.get("setName", "")),
        "name": clean_text(row.get("productName", "")),
        "rarity": clean_text(row.get("rarity", "")),
        "type": clean_text(row.get("subTypeName", "")),
        "market": market,
        "mid": parse_price(row.get("midPrice", "")),
        "low": parse_price(row.get("lowPrice", "")),
        "high": parse_price(row.get("highPrice", "")),
        "priceStatus": "ok" if market is not None else "missing",
    }
    # Keep keys stable for firmware, but remove empty descriptive fields to save bytes.
    return card


def select_cards(
    rows: Iterable[Dict[str, str]],
    limit: int,
    require_market_price: bool,
    product_id: Optional[str] = None,
) -> tuple[List[Dict[str, Any]], int, int]:
    selected: List[Dict[str, Any]] = []
    total_rows = 0
    skipped_missing_price_before_limit = 0
    seen_variant_keys = set()

    for row in rows:
        total_rows += 1
        if product_id is not None and row.get("productId") != product_id:
            continue

        market = parse_price(row.get("marketPrice", ""))

        # Keep reading after the display feed is full so totalRows describes the
        # complete source CSV, not only the rows scanned before the limit.
        feed_is_full = len(selected) >= limit

        if require_market_price and market is None:
            if not feed_is_full:
                skipped_missing_price_before_limit += 1
            continue
        if feed_is_full:
            continue

        # Keep one row per productId + subtype. This preserves Normal/Holo/Reverse variants
        # while avoiding accidental duplicates if the source ever repeats rows.
        key = (row.get("productId", ""), row.get("subTypeName", ""))
        if key in seen_variant_keys:
            continue
        seen_variant_keys.add(key)

        selected.append(row_to_card(row))

    return selected, total_rows, skipped_missing_price_before_limit


def generate(
    input_path: Path,
    output_path: Path,
    limit: int,
    require_market_price: bool,
    product_id: Optional[str] = None,
) -> Dict[str, Any]:
    with input_path.open("r", newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        cards, total_rows, skipped_missing_price = select_cards(reader, limit, require_market_price, product_id)

    payload: Dict[str, Any] = {
        "schemaVersion": 1,
        "source": "tcgcsv",
        "sourceUpdatedAt": fetch_source_updated_at(),
        "generatedAt": datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z"),
        "totalRows": total_rows,
        "cardsIncluded": len(cards),
        "selection": {
            "limit": limit,
            "productId": int(product_id) if product_id and product_id.isdigit() else product_id,
            "requireMarketPrice": require_market_price,
            "order": "exact_product_id" if product_id else "csv_order_newest_groups_first",
            "skippedMissingPriceBeforeLimit": skipped_missing_price,
        },
        "cards": cards,
    }

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        json.dumps(payload, ensure_ascii=False, separators=(",", ":")),
        encoding="utf-8",
    )
    return payload


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate ESP32/e-paper JSON from Pokémon price CSV")
    parser.add_argument("--input", required=True, help="Input full CSV path")
    parser.add_argument("--output", required=True, help="Output JSON path")
    parser.add_argument("--limit", type=int, default=300, help="Maximum cards to include (default: 300)")
    parser.add_argument("--product-id", help="Only include this TCGplayer productId, useful for a single-card MVP")
    parser.add_argument(
        "--include-missing-price",
        action="store_true",
        help="Include rows with no marketPrice; default skips them to keep the feed useful for display",
    )
    args = parser.parse_args()

    payload = generate(
        input_path=Path(args.input),
        output_path=Path(args.output),
        limit=args.limit,
        require_market_price=not args.include_missing_price,
        product_id=args.product_id,
    )
    print(
        f"Wrote {args.output}: {payload['cardsIncluded']} cards from {payload['totalRows']} rows; "
        f"sourceUpdatedAt={payload['sourceUpdatedAt']}"
    )


if __name__ == "__main__":
    main()
